// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentInterviewManagementSystem.Models;

#nullable disable

namespace RecruitmentInterviewManagementSystem.Migrations
{
    [DbContext(typeof(FakeTopcvContext))]
    [Migration("20260310143111_v13")]
    partial class v13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobSkill", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId", "SkillId")
                        .HasName("PK__JobSkill__689C99DA801B13C1");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills", (string)null);
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Infastructure.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPopup")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Infastructure.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Infastructure.Models.BookingLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("BookingLink");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Infastructure.Models.Interviews", b =>
                {
                    b.Property<Guid>("IdInterview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Decision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdApplication")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdInterviewSlot")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoftSkillScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TechnicalScore")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdInterview");

                    b.HasIndex("IdApplication");

                    b.HasIndex("IdInterviewSlot")
                        .IsUnique();

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Infastructure.Models.InterviewsSlots", b =>
                {
                    b.Property<Guid>("IdInterviewSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCompany")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdInterviewSlot");

                    b.ToTable("InterviewSlots");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Cvid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CVId");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Applicat__3214EC07582676B4");

                    b.HasIndex("CandidateId");

                    b.HasIndex("Cvid");

                    b.HasIndex(new[] { "JobId", "CandidateId" }, "UQ_Application")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CurrentSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<decimal?>("DesiredSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("JobLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Candidat__3214EC071E63B6B1");

                    b.HasIndex(new[] { "UserId" }, "UQ__Candidat__1788CC4DB5D0361F")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CandidateSkill", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.HasKey("CandidateId", "SkillId")
                        .HasName("PK__Candidat__B2A99284D1268521");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Companie__3214EC07BB89D494");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CompanySubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("RemainingPost")
                        .HasColumnType("int");

                    b.Property<Guid>("ServicePackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__CompanyS__3214EC074F42971F");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ServicePackageId");

                    b.ToTable("CompanySubscriptions");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Cv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("CurrentSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("EducationSummary")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Field")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TemplateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__CVs__3214EC074E6E5E70");

                    b.HasIndex("CandidateId");

                    b.ToTable("CVs", (string)null);
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CvCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CertificateName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("Cvid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CVId");

                    b.Property<DateOnly?>("ExpiredDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Organization")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__CV_Certi__3214EC075FC69D71");

                    b.HasIndex("Cvid");

                    b.ToTable("CV_Certificates", (string)null);
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CvEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("Cvid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CVId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Major")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__CV_Educa__3214EC070F7A288C");

                    b.HasIndex("Cvid");

                    b.ToTable("CV_Educations", (string)null);
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CvExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("Cvid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CVId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__CV_Exper__3214EC078322F34E");

                    b.HasIndex("Cvid");

                    b.ToTable("CV_Experiences", (string)null);
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CvProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("Cvid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CVId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__CV_Proje__3214EC07D91F7C40");

                    b.HasIndex("Cvid");

                    b.ToTable("CV_Projects", (string)null);
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CvSkill", b =>
                {
                    b.Property<Guid>("Cvid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CVId");

                    b.Property<string>("SkillName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.HasKey("Cvid", "SkillName")
                        .HasName("PK__CV_Skill__BB2F39F444CE8160");

                    b.ToTable("CV_Skills", (string)null);
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.EmployerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Employer__3214EC07541EB4AD");

                    b.HasIndex("CompanyId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Employer__1788CC4D61E45335")
                        .IsUnique();

                    b.ToTable("EmployerProfiles");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.JobPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Benefit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Requirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__JobPosts__3214EC07FC730E1F");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC07ABC2DDDE");

                    b.HasIndex("EmployerId");

                    b.HasIndex(new[] { "OrderCode" }, "UQ__Orders__999B5229983DD7F5")
                        .IsUnique()
                        .HasFilter("[OrderCode] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ServicePackageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__OrderIte__3214EC0752E81A21");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServicePackageId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC07E13485CE");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JwtId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC07A8E2136C");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.SavedJob", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("CandidateId", "JobId")
                        .HasName("PK__SavedJob__EF05F290E9B5F635");

                    b.HasIndex("JobId");

                    b.ToTable("SavedJobs");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.ServicePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxPost")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__ServiceP__3214EC07AFF571BD");

                    b.ToTable("ServicePackages");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Skills__3214EC0767E0594D");

                    b.HasIndex(new[] { "Name" }, "UQ__Skills__737584F6343A08C9")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("default_salt_value");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC074C9A6D4F");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105348C8C58BF")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JobSkill", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.JobPost", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK__JobSkills__JobId__6EF57B66");

                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__JobSkills__Skill__6FE99F9F");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Infastructure.Models.BookingLink", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("BookingLinks")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Infastructure.Models.Interviews", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Application", "application")
                        .WithMany("Interviews")
                        .HasForeignKey("IdApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentInterviewManagementSystem.Infastructure.Models.InterviewsSlots", "InterviewsSlots")
                        .WithOne("Interview")
                        .HasForeignKey("RecruitmentInterviewManagementSystem.Infastructure.Models.Interviews", "IdInterviewSlot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewsSlots");

                    b.Navigation("application");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Application", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.CandidateProfile", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__Candi__123EB7A3");

                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Cv", "Cv")
                        .WithMany("Applications")
                        .HasForeignKey("Cvid")
                        .IsRequired()
                        .HasConstraintName("FK__Applicatio__CVId__1332DBDC");

                    b.HasOne("RecruitmentInterviewManagementSystem.Models.JobPost", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__JobId__114A936A");

                    b.Navigation("Candidate");

                    b.Navigation("Cv");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CandidateProfile", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("RecruitmentInterviewManagementSystem.Models.CandidateProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CandidateSkill", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.CandidateProfile", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__Candidate__Candi__72C60C4A");

                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__Candidate__Skill__73BA3083");

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CompanySubscription", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Company", "Company")
                        .WithMany("CompanySubscriptions")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK__CompanySu__Compa__2FCF1A8A");

                    b.HasOne("RecruitmentInterviewManagementSystem.Models.ServicePackage", "ServicePackage")
                        .WithMany("CompanySubscriptions")
                        .HasForeignKey("ServicePackageId")
                        .IsRequired()
                        .HasConstraintName("FK__CompanySu__Servi__30C33EC3");

                    b.Navigation("Company");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Cv", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.CandidateProfile", "Candidate")
                        .WithMany("Cvs")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__CVs__CandidateId__797309D9");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CvCertificate", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Cv", "Cv")
                        .WithMany("CvCertificates")
                        .HasForeignKey("Cvid")
                        .IsRequired()
                        .HasConstraintName("FK__CV_Certifi__CVId__0B91BA14");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CvEducation", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Cv", "Cv")
                        .WithMany("CvEducations")
                        .HasForeignKey("Cvid")
                        .IsRequired()
                        .HasConstraintName("FK__CV_Educati__CVId__01142BA1");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CvExperience", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Cv", "Cv")
                        .WithMany("CvExperiences")
                        .HasForeignKey("Cvid")
                        .IsRequired()
                        .HasConstraintName("FK__CV_Experie__CVId__7D439ABD");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CvProject", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Cv", "Cv")
                        .WithMany("CvProjects")
                        .HasForeignKey("Cvid")
                        .IsRequired()
                        .HasConstraintName("FK__CV_Project__CVId__04E4BC85");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CvSkill", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Cv", "Cv")
                        .WithMany("CvSkills")
                        .HasForeignKey("Cvid")
                        .IsRequired()
                        .HasConstraintName("FK__CV_Skills__CVId__07C12930");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.EmployerProfile", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Company", "Company")
                        .WithMany("EmployerProfiles")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_Employer_Company");

                    b.HasOne("RecruitmentInterviewManagementSystem.Models.User", "User")
                        .WithOne("EmployerProfile")
                        .HasForeignKey("RecruitmentInterviewManagementSystem.Models.EmployerProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Employer_User");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.JobPost", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Company", "Company")
                        .WithMany("JobPosts")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Order", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.EmployerProfile", "Employer")
                        .WithMany("Orders")
                        .HasForeignKey("EmployerId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__Employer__22751F6C");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.OrderItem", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Order__2645B050");

                    b.HasOne("RecruitmentInterviewManagementSystem.Models.ServicePackage", "ServicePackage")
                        .WithMany("OrderItems")
                        .HasForeignKey("ServicePackageId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Servi__2739D489");

                    b.Navigation("Order");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Payment", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__OrderI__2B0A656D");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.RefreshToken", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.SavedJob", b =>
                {
                    b.HasOne("RecruitmentInterviewManagementSystem.Models.CandidateProfile", "Candidate")
                        .WithMany("SavedJobs")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__SavedJobs__Candi__17036CC0");

                    b.HasOne("RecruitmentInterviewManagementSystem.Models.JobPost", "Job")
                        .WithMany("SavedJobs")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK__SavedJobs__JobId__17F790F9");

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Infastructure.Models.InterviewsSlots", b =>
                {
                    b.Navigation("Interview");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Application", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.CandidateProfile", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("BookingLinks");

                    b.Navigation("CandidateSkills");

                    b.Navigation("Cvs");

                    b.Navigation("SavedJobs");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Company", b =>
                {
                    b.Navigation("CompanySubscriptions");

                    b.Navigation("EmployerProfiles");

                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Cv", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CvCertificates");

                    b.Navigation("CvEducations");

                    b.Navigation("CvExperiences");

                    b.Navigation("CvProjects");

                    b.Navigation("CvSkills");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.EmployerProfile", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.JobPost", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("SavedJobs");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.ServicePackage", b =>
                {
                    b.Navigation("CompanySubscriptions");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.Skill", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("RecruitmentInterviewManagementSystem.Models.User", b =>
                {
                    b.Navigation("CandidateProfile");

                    b.Navigation("EmployerProfile");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
